server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/sampledb
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog.xml
    user: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
    properties:
      hibernate:
#SET TO TRUE IF YOU WANT TO ENABLE HIBERNATE LOGGING
        show_sql: false
        format_sql: true
        use_sql_comments: false

#UNCOMMENT LOGGING PART IF YOU WANT TO ENABLE HIBERNATE LOGGING
#logging:
#    level:
#        org:
#            hibernate:
#                type: trace
